# Plugins defined by this project
[plugins]
mega-android-library = { id = "mega.android.library", version = "unspecified" }
mega-android-room = { id = "mega.android.room", version = "unspecified" }
mega-android-test = { id = "mega.android.test", version = "unspecified" }
mega-android-app = { id = "mega.android.app", version = "unspecified" }
mega-jvm-test = { id = "mega.jvm.test", version = "unspecified" }
mega-jvm-library = { id = "mega.jvm.library", version = "unspecified" }
mega-android-library-jacoco = { id = "mega.android.library.jacoco", version = "unspecified" }
mega-jvm-jacoco = { id = "mega.jvm.jacoco", version = "unspecified" }
mega-android-application-jacoco = { id = "mega.android.application.jacoco", version = "unspecified" }

