[versions]
accompanist = "0.32.0"
accompanist-pager = "0.30.1"
accompanist-systemui = "0.23.1"
autovalue = "1.10.4"
firebase = "33.1.1"
firebase-app-distribution = "16.0.0-beta13"
flexbox = "3.0.0"
gson = "2.10.1"
hilt = "2.51"
material = "1.12.0"
maps-utils = "0.5"
maps-compose = "6.1.0"
play-review = "2.0.1"
play-update = "2.1.0"
protobuff = "3.22.3"
services-ads = "23.3.0"
services-location = "21.3.0"
services-maps = "18.2.0"
services-mlkit-document-scanner = "16.0.0-beta1"
zxing = "3.4.1"
code-scanner = "16.1.0"
media3 = "1.3.1"
install-referrer = "2.2"
tink = "1.8.0"
guava = "33.0.0-jre"

[libraries]
accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist-pager" }
accompanist-flowlayout = { module = "com.google.accompanist:accompanist-flowlayout", version.ref = "accompanist" }
accompanist-placeholder = { module = "com.google.accompanist:accompanist-placeholder-material", version.ref = "accompanist" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
accompanist-navigationmaterial = { module = "com.google.accompanist:accompanist-navigation-material", version.ref = "accompanist" }
accompanist-navigationanimation = { module = "com.google.accompanist:accompanist-navigation-animation", version.ref = "accompanist" }
accompanist-systemui = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist-systemui" }
autovalue = { module = "com.google.auto.value:auto-value", version.ref = "autovalue" }
autovalue-annotations = { module = "com.google.auto.value:auto-value-annotations", version.ref = "autovalue" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics"}
firebase-app-distribution = { module = "com.google.firebase:firebase-appdistribution", version.ref = "firebase-app-distribution" }
firebase-crashlytics-ndk = { group = "com.google.firebase", name = "firebase-crashlytics-ndk" }
firebase-crashlytics-ktx = { group = "com.google.firebase", name = "firebase-crashlytics-ktx" }
firebase-messaging-ktx = { group = "com.google.firebase", name = "firebase-messaging-ktx" }
firebase-perf-ktx = { group = "com.google.firebase", name = "firebase-perf-ktx" }
flexbox = { module = "com.google.android.flexbox:flexbox", version.ref = "flexbox" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
hilt-core = { module = "com.google.dagger:hilt-core", version.ref = "hilt" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-android-test = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }
maps-utils = { module = "com.google.maps.android:android-maps-utils", version.ref = "maps-utils" }
maps-compose = { module = "com.google.maps.android:maps-compose", version.ref = "maps-compose" }
material = { module = "com.google.android.material:material", version.ref = "material" }
play-review = { module = "com.google.android.play:review", version.ref = "play-review" }
play-review-ktx = { module = "com.google.android.play:review-ktx", version.ref = "play-review" }
play-update = { module = "com.google.android.play:app-update", version.ref = "play-update" }
play-update-ktx = { module = "com.google.android.play:app-update-ktx", version.ref = "play-update" }
protobuff = { module = "com.google.protobuf:protobuf-java", version.ref = "protobuff" }
services-ads = { module = "com.google.android.gms:play-services-ads", version.ref = "services-ads" }
services-location = { module = "com.google.android.gms:play-services-location", version.ref = "services-location" }
services-maps = { module = "com.google.android.gms:play-services-maps", version.ref = "services-maps" }
services-mlkit-document-scanner = { module = "com.google.android.gms:play-services-mlkit-document-scanner", version.ref = "services-mlkit-document-scanner"}
zxing = { module = "com.google.zxing:core", version.ref = "zxing" }
code-scanner = { module = "com.google.android.gms:play-services-code-scanner", version.ref = "code-scanner" }
media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3" }
media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3" }
install-referrer = { module = "com.android.installreferrer:installreferrer", version.ref = "install-referrer" }
tink = { module = "com.google.crypto.tink:tink-android", version.ref = "tink" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }

[bundles]
firebase-bom = ["firebase-crashlytics-ndk", "firebase-crashlytics-ktx", "firebase-messaging-ktx", "firebase-perf-ktx"]
