[versions]
anko = "0.10.8"
bannerviewpager = "3.4.0"
billing-client = "6.0.1"
coil = "2.3.0"
coroutines = "1.6.4"
desugar = "2.0.3"
fresco = "2.6.0"
javax = "1"
kotlin = "1.9.10"
kotlin-ktx = "1.10.1"
liveeventbus = "1.7.3"
logging-logback = "2.0.0"
logging-slf4j = "1.7.30"
logging-timber = "5.0.1"
retrofit = "2.9.0"
rx-android = "3.0.0"
rx-coroutines = "1.6.4"
rx-java = "3.0.6"
rx-kotlin = "3.0.1"
simplestorage = "1.1.0"
compose-state-events = "1.2.3"
kotlinpoet = "1.14.2"
xray = "1.0"
nocturn = "1.0"
karma = "1.3"
sqlcipher = "4.5.4"

[libraries]
anko-commons = { module = "org.jetbrains.anko:anko-commons", version.ref = "anko" }
bannerviewpager = { module = "com.github.zhpanvip:BannerViewPager", version.ref = "bannerviewpager" }
billing-client = { module = "com.android.billingclient:billing", version.ref = "billing-client" }
billing-client-ktx = { module = "com.android.billingclient:billing-ktx", version.ref = "billing-client" }
blurry = 'jp.wasabeef:blurry:2.1.0'
code-scanner = 'com.budiyev.android:code-scanner:1.8.3'
coil = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-gif = { module = "io.coil-kt:coil-gif", version.ref = "coil" }
coil-svg = { module = "io.coil-kt:coil-svg", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
collapsingtoolbar = 'net.opacapp:multiline-collapsingtoolbar:27.1.1'
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
desugar = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar" }
documentscanner = 'com.github.meganz.AndroidDocumentScanner:documentscanner:2.0.12'
facebook-inferannotation = "com.facebook.infer.annotation:infer-annotation:0.18.0"
fresco = { module = "com.facebook.fresco:fresco", version.ref = "fresco" }
fresco-gif = { module = "com.facebook.fresco:animated-gif", version.ref = "fresco" }
fresco-webp = { module = "com.facebook.fresco:animated-webp", version.ref = "fresco" }
fresco-webpsupport = { module = "com.facebook.fresco:webpsupport", version.ref = "fresco" }
javax-inject = { module = "javax.inject:javax.inject", version.ref = "javax" }
kotlin-ktx = { module = "androidx.core:core-ktx", version.ref = "kotlin-ktx" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-stdlib-jdk7 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
logging-logback = { module = "com.github.tony19:logback-android", version.ref = "logging-logback" }
logging-slf4j = { module = "org.slf4j:slf4j-api", version.ref = "logging-slf4j" }
logging-timber = { module = "com.jakewharton.timber:timber", version.ref = "logging-timber" }
namedregexp = 'com.github.tony19:named-regexp:0.2.5'
parallaxscroll = 'com.github.nirhart:parallaxscroll:1.0'
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
rx-android = { module = "io.reactivex.rxjava3:rxandroid", version.ref = "rx-android" }
rx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-rx3", version.ref = "rx-coroutines" }
rx-java = { module = "io.reactivex.rxjava3:rxjava", version.ref = "rx-java" }
rx-kotlin = { module = "io.reactivex.rxjava3:rxkotlin", version.ref = "rx-kotlin" }
shimmerlayout = 'io.supercharge:shimmerlayout:2.1.0'
shortcutbadger = 'me.leolin:ShortcutBadger:1.1.22'
simplestorage = { module = "com.anggrayudi:storage", version.ref = "simplestorage" }
stickyheader = 'com.brandongogetap:stickyheaders:0.6.1'
vdurmont-emoji = 'com.vdurmont:emoji-java:4.0.0'
compose-state-events = { module = "com.github.leonard-palm:compose-state-events", version.ref = "compose-state-events" }
mega-analytics = "mega.privacy.mobile:analytics-events-android:+"
kotlinpoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinpoet" }
balloon = "com.github.skydoves:balloon-compose:1.5.4"
xray = { module = "mega.privacy.android.xray:xray", version.ref = "xray" }
nocturn = { module = "mega.privacy.android.nocturn:nocturn", version.ref = "nocturn" }
karma-annotation = { module = "com.mega.karma:annotation", version.ref = "karma" }
karma-compiler = { module = "com.mega.karma:compiler", version.ref = "karma" }
karma-core = { module = "com.mega.karma:core", version.ref = "karma" }
sqlcipher = { module = "net.zetetic:android-database-sqlcipher", version.ref = "sqlcipher" }

[bundles]
fresco = ["fresco", "fresco-gif", "fresco-webp", "fresco-webpsupport"]
logging = ["logging-slf4j", "logging-logback", "logging-timber"]
unit-test = ["coroutines-test", "kotlin-test"]
rx = ["rx-android", "rx-coroutines", "rx-java", "rx-kotlin"]