[versions]
bannerviewpager = "3.5.12"
billing-client = "8.0.0"
coil = "2.7.0"
coil3 = "3.2.0"
concurrent-futures-ktx = "1.1.0"
coroutines = "1.10.1"
javax = "1"
kotlin = "2.1.0"
kotlin-ktx = "1.15.0"
logging-logback = "2.0.0"
logging-slf4j = "1.7.36"
logging-timber = "5.0.1"
retrofit = "2.9.0"
simplestorage = "1.1.0"
compose-state-events = "2.1.1"
kotlinpoet = "1.14.2"
xray = "1.0"
nocturn = "1.0"
karma = "1.3"
kotlin-serialisation = "1.8.1"
eclipse-jgit = "6.6.0.202305301015-r"
json = "20240303"
mega-telephoto = "0.16.0"
telephoto = "0.16.0"
mega-core-ui = "2.170.20250708103141"
kotlinx-collections-immutable = "0.3.7"
commonmark-java = "0.24.0"
ucropnedit = "4.1.4"

[libraries]
bannerviewpager = { module = "com.github.zhpanvip:BannerViewPager", version.ref = "bannerviewpager" }
billing-client = { module = "com.android.billingclient:billing", version.ref = "billing-client" }
billing-client-ktx = { module = "com.android.billingclient:billing-ktx", version.ref = "billing-client" }
blurry = 'jp.wasabeef:blurry:4.0.1'
coil = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-gif = { module = "io.coil-kt:coil-gif", version.ref = "coil" }
coil-svg = { module = "io.coil-kt:coil-svg", version.ref = "coil" }
coil-video = { module = "io.coil-kt:coil-video", version.ref = "coil" }
coil3-gif = { module = "io.coil-kt.coil3:coil-gif", version.ref = "coil3" }
coil3-svg = { module = "io.coil-kt.coil3:coil-svg", version.ref = "coil3" }
coil3-video = { module = "io.coil-kt.coil3:coil-video", version.ref = "coil3" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil3" }
concurrent-futures-ktx = { module = "androidx.concurrent:concurrent-futures-ktx", version.ref = "concurrent-futures-ktx" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
javax-inject = { module = "javax.inject:javax.inject", version.ref = "javax" }
kotlin-ktx = { module = "androidx.core:core-ktx", version.ref = "kotlin-ktx" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-stdlib-jdk7 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
logging-logback = { module = "com.github.tony19:logback-android", version.ref = "logging-logback" }
logging-slf4j = { module = "org.slf4j:slf4j-api", version.ref = "logging-slf4j" }
logging-timber = { module = "com.jakewharton.timber:timber", version.ref = "logging-timber" }
namedregexp = 'com.github.tony19:named-regexp:0.2.5'
parallaxscroll = 'com.github.nirhart:parallaxscroll:1.0'
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
shimmerlayout = 'io.supercharge:shimmerlayout:2.1.0'
simplestorage = { module = "com.anggrayudi:storage", version.ref = "simplestorage" }
vdurmont-emoji = 'com.vdurmont:emoji-java:5.1.1'
compose-state-events = { module = "com.github.leonard-palm:compose-state-events", version.ref = "compose-state-events" }
mega-analytics = "mega.privacy.mobile:analytics-events-android:+"
kotlinpoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinpoet" }
balloon = "com.github.skydoves:balloon-compose:1.6.4"
xray = { module = "mega.privacy.android.xray:xray", version.ref = "xray" }
nocturn = { module = "mega.privacy.android.nocturn:nocturn", version.ref = "nocturn" }
karma-annotation = { module = "com.mega.karma:annotation", version.ref = "karma" }
karma-compiler = { module = "com.mega.karma:compiler", version.ref = "karma" }
karma-core = { module = "com.mega.karma:core", version.ref = "karma" }
kotlin-serialisation = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlin-serialisation"}
eclipse-jgit = { module = "org.eclipse.jgit:org.eclipse.jgit", version.ref = "eclipse-jgit"}
eclipse-jgit-ssh-jsch = { module = "org.eclipse.jgit:org.eclipse.jgit.ssh.jsch", version.ref = "eclipse-jgit"}
json = { module = "org.json:json", version.ref = "json"}
zoomable-telephoto = { module = "me.saket.telephoto.mega:zoomable", version.ref = "mega-telephoto" }
zoomable-image-coil = { module = "me.saket.telephoto.mega:zoomable-image-coil3", version.ref = "mega-telephoto" }
zoomable-image-core = { module = "me.saket.telephoto.mega:zoomable-image-core", version.ref = "mega-telephoto" }
zoomable-image-subsampling-image = { module = "me.saket.telephoto.mega:sub-sampling-image", version.ref = "mega-telephoto" }
telephoto-flick = { module = "me.saket.telephoto:flick", version.ref = "telephoto" }
mega-core-ui = { group = "mega.android.core", name  = "ui", version.ref = "mega-core-ui" }
mega-core-ui-tokens = { group = "mega.android.core", name  = "ui-tokens", version.ref = "mega-core-ui"}
kotlinx-collections-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinx-collections-immutable" }
commonmark-java = {module = "org.commonmark:commonmark", version.ref = "commonmark-java"}
ucropnedit = { module = "com.github.jens-muenker.mega:ucropnedit", version.ref = "ucropnedit" }

[bundles]
logging = ["logging-slf4j", "logging-logback", "logging-timber"]
unit-test = ["coroutines-test", "kotlin-test"]
