[versions]
firebase-crashlytics = "3.0.2"
firebase-performance = "1.4.2"
firebase-app-distribution = "5.0.0"
gradle = "8.5.0"
google-services = "4.4.2"
hilt = "2.51"
jacoco = "0.8.11"
jfrog = "5.2.0"
android-junit5 = "1.10.0.0"
kotlin = "1.9.24"
lint = "30.2.2"
navigation = "2.7.7"
paparazzi = "1.3.2"
ksp = "1.9.24-1.0.20"
megagradle = "0.36.20240709040144"
jfrog-artifactory = "5.2.0"

[libraries]
build-tools = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "firebase-crashlytics" }
firebase-performance = { module = "com.google.firebase:perf-plugin", version.ref = "firebase-performance" }
firebase-app-distribution = { module = "com.google.firebase:firebase-appdistribution-gradle", version.ref = "firebase-app-distribution" }
google-services = { module = "com.google.gms:google-services", version.ref = "google-services" }
hilt-android = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
jacoco = { module = "org.jacoco:org.jacoco.core", version.ref = "jacoco" }
jfrog = { module = "org.jfrog.buildinfo:build-info-extractor-gradle", version.ref = "jfrog" }
junit5 = { module = "de.mannodermaus.gradle.plugins:android-junit5", version.ref = "android-junit5" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
navigation-safeargs = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "navigation" }
paparazzi = { module = "app.cash.paparazzi:paparazzi-gradle-plugin", version.ref = "paparazzi" }
ksp-gradle-plugin = { module = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }

[plugins]
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
jfrog-artifactory = { id = "com.jfrog.artifactory", version.ref = "jfrog-artifactory" }
mega-artifactory-publish-convention = { id = "mega.artifactory.publish.convention", version.ref = "megagradle" }
mega-android-release = { id = "mega.android.release", version.ref = "megagradle" }
mega-android-cicd = { id = "mega.android.cicd", version.ref = "megagradle" }
de-mannodermaus-android-junit5 = { id = "de.mannodermaus.android-junit5", version.ref = "android-junit5" }
